In [1]:
import pandas as pd 
import numpy as np

Рабочий диапазон амплитуд, определенный экспериментально:
За 1 минуту 32 с амплитуда упала примерно в 1,5 раза. Период колебания приблизительно 4.38 с (21 колебание)

In [2]:
# измерение параметров установки
l = 216 # cm
r = 0
R = 0
# момент инерции платформы
t_0 = 60+32+0.77
n_0 = 21
T = t_0/n_0

In [3]:
# измерение момента инерции тела 1 (круг)
d = 170.5 # mm, диаметр
m = 587.9 # г
moment_1 = pd.DataFrame({"t, c" : [60+58+0.96, 60+38+0.8, 60+19+0.19], "n" : [30, 25, 20]})
moment_1

     t, c   n
0  118.96  30
1   98.80  25
2   79.19  20

In [4]:
# измерение момента инерции тела 2 (брусок)
d = 209.4 # mm, длина
w = 28 # mm, ширина
h = 27.6 # mm, высота
m = 12730
moment_2 = pd.DataFrame({"t, c" : [60+52+0.54, 60+33+0.55, 60+14+0.99], "n" : [30, 25, 20]})
moment_2

     t, c   n
0  112.54  30
1   93.55  25
2   74.99  20

In [5]:
# измерение момента инерции двух тел 1 и 2 вместе
moment_1_and_2 = pd.DataFrame({'t, с' : [60+47+0.56, 60+29+0.64, 60+12], "n" : [30, 25, 20]})
moment_1_and_2
moment_1_and_2.to_latex(escape=True)

'\\begin{tabular}{lrr}\n\\toprule\n & t, с & n \\\\\n\\midrule\n0 & 107.560000 & 30 \\\\\n1 & 89.640000 & 25 \\\\\n2 & 72.000000 & 20 \\\\\n\\bottomrule\n\\end{tabular}\n'

In [ ]:
# измерение момента инерции разрезанного диска
m_1 = 763.5 # г
m_2 = 764 # г
d_disk = 90.9 # mm, диаметр
w_disk = 27.9 # mm, толщина
# h - расстояние от центра половинки до центра платформы в миллиметрах
moment_disk = pd.DataFrame({'h': [0, 5, 15, 30, 40, 55, 65], 't, с' : [60+17+0.25, 60+17+0.06, 60+18+0.34, 60+22+0.46, 60+26+0.02, 60+33+0.36, 60+39+0.02], "n" : [25, 25, 25, 25, 25, 25, 25]})
moment_disk

    h   t, с   n
0   0  77.25  25
1   5  77.06  25
2  15  78.34  25
3  30  82.46  25
4  40  86.02  25
5  55  93.36  25
6  65  99.02  25